### ISSUE TITLE
 Unable to find configuration

### ISSUE THREAD

**Issue by zemul** [Ackerr/lab#20]
➜  ~ lab config
open config.toml: no such file or directory

**Comment by ackerr** [comment]
可以先用v0.2.15，最新版支持多server引入了这个问题

**Comment by me10zyl** [comment]
```
PS E:\git\lab> lab config
set Gitlab token first, use `lab config`
```

Used in windows 10...

**Comment by zemul** [comment]
> 可以先用v0.2.15，最新版支持多server引入了这个问题

thank you

**Comment by Ackerr** [comment]
> 
> Used in windows 10...


> > 可以先用v0.2.15，最新版支持多server引入了这个问题
> 
> thank you

更新一下再试试

**Comment by ackerr** [comment]
> ```
> PS E:\git\lab> lab config
> set Gitlab token first, use `lab config`
> ```
> 
> Used in windows 10...

试试更新一下版本。还有问题的话，可以手动编辑一下 ~/.config/lab/config.toml
身边暂时没windows的电脑，晚点看看，谢谢反馈

**Comment by ackerr** [comment]
@me10zyl @zemul 发布了v0.2.19. 修掉了你们的问题.
