### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by ghost** [Ackerr/lab#25]
I followed the README.md and this happens:

![image](https://user-images.githubusercontent.com/53082621/126322013-f9511a77-b943-44d6-9c98-ce5761520f71.png)

When I run the `go get` it downloads fine (Screenshot is after)
Then, I try to run `lab` or `lab config` and it doesn't find it

**Comment by ackerr** [comment]
Check $GOPATH  in your $PATH

**Comment by ghost** [comment]
Found that it does exist indeed and it works fine.
![image](https://user-images.githubusercontent.com/53082621/126322757-78f62b6c-76fa-43f7-9e49-8fd749e73e6e.png)

Need to figure out why I can't call it directly in the terminal because I do have this.

![image](https://user-images.githubusercontent.com/53082621/126322836-ab3c770d-f8ec-40b3-9f11-8060f1ed3581.png)

You know how to fix this?

**Comment by ghost** [comment]
aaaaaaaaagh, wait. The path `lab` is in is `/home/thejoker/go/bin` not the one from the last image
