### ISSUE TITLE
希望支持 gitea 风格的 subpage

### ISSUE THREAD

**Issue by liriansu-opus** [Ackerr/lab#31]
目前 subpage 会使用 gitlab 风格，加上 `/-/`，
但是 gitea 没有中间的这一横…

举例，一个 merge requests subpage 的例子是 https://try.gitea.io/CodingDoctor/for-gitea-issue-8299/pulls

**Comment by ackerr** [comment]
Get，lab open只适配了gitlab跟github两个，之前直接硬编码了一下
![image](https://github.com/ackerr/lab/assets/35414361/96c08c4d-033c-4b22-b2cb-970a6d426401)

**Comment by ackerr** [comment]
fixed in https://github.com/ackerr/lab/commit/15a551f354df295d561b7e046a0f6d0f9644a581
