### ISSUE TITLE
我希望 lab clone 可以按照结构来克隆项目

### ISSUE THREAD

**Issue by liriansu-opus** [Ackerr/lab#8]
```
- gitlab.com
- gitlab.lilithgames.com
  - be
    - davinci
    - einstein
  - fe
    - homepage
```

比如目录结构是这样的时候，`lab clone git@gitlab.lilithgames.com:be/newproject` 会自动地放在 `$CODE/gitlab.lilithgames.com/be/newproject` 里
（这样也跟 gopath 里的结构是一样的

**Comment by Ehco1996** [comment]
+1

**Comment by liriansu-opus** [comment]
顺便求一下 clone post fix 的配置项。

比如我有这么一个需求：
就是自己的全局 gitconfig 是用 gmail.com 邮箱的，
但是公司的项目需要用公司的用户名以及邮箱。

希望 clone 后能自动地设置一下
